name: main
on: push
env:
  PYTHON_VERSION: 3.8

jobs:
  test-infra:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2.2.2
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: test get-function
        run: cd resumeAWS/getFunction && python3 test.py -v && cd ..
      - name: test put-function
        run: cd resumeAWS/putFunction && python3 test.py -v && cd ..
